### ISSUE TITLE
缺少动态库

### ISSUE THREAD

**Issue by mzwrt** [typecho/Dockerfile#44] opened 2024-04-18 18:32 UTC
Joyqi/typecho:nightly-php8.2-apache

stderr: [18-Apr-2024 18:08:22 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/gd.so (libpng16.so.16: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

stderr: [18-Apr-2024 18:08:23 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so (libzip.so.4: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829//usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829//usr/local/lib/php/extensions/no-debug-non-zts-20220829/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

暂时解决方案
apt update && apt install libzip4 libpng16-16

希望后期修复问题

**Comment by sy-records** [comment] 2024-10-11 05:44
Duplicate of #48

**Closed by sy-records** 2024-10-11 05:44 UTC
